name: Build and Deploy

on:
  workflow_dispatch: {}

env:
  AWS_REGION: eu-west-1
  S3BUCKET: aws-code-deploy-ec2

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          role-session-name: GitHub-Action-Role
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: chmod
        run: chmod -R +x ./.github

      - name: Build and Package Maven
        id: package
        run:  mvn -Dmaven.test.skip=true clean install --file pom.xml

      - name: Upload Artifact to s3
        run: aws s3 cp *.zip s3://${{ env.S3BUCKET }}/